version: "3.7"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3007:3007"
    volumes:
      - "/app/node_modules"
      - "./:/app"